// The 38 municipalities of Kosovo, from the project's GeoJSON
// (public/kosovo.geojson, sourced from Learti82/GeoJSON-Kosova). Used to power
// the city filter; the full GeoJSON geometry is kept in public/ for a future
// interactive map view.

export const KOSOVO_MUNICIPALITIES: string[] = [
  "Deçan",
  "Dragash",
  "Ferizaj",
  "Fushë Kosovë",
  "Gjakovë",
  "Gjilan",
  "Gllogoc",
  "Graçanicë",
  "Hani i Elezit",
  "Istog",
  "Junik",
  "Kamenicë",
  "Kaçanik",
  "Klinë",
  "Kllokot",
  "Leposaviq",
  "Lipjan",
  "Malishevë",
  "Mamushë",
  "Mitrovicë e Jugut",
  "Mitrovicë e Veriut",
  "Novobërdë",
  "Obiliq",
  "Partesh",
  "Pejë",
  "Podujevë",
  "Prishtinë",
  "Prizren",
  "Rahovec",
  "Ranillug",
  "Shtime",
  "Shtërpcë",
  "Skënderaj",
  "Suharekë",
  "Viti",
  "Vushtrri",
  "Zubin Potok",
  "Zveçan",
];
